version: '3.8'

services:
  app:
    image: amazoncorretto:17-alpine-jdk
    restart: always
    ports:
      - '8088:4040'
    environment:
      DB_CONNECTION_IP: "postgres_hostname"
      DB_CONNECTION_PORT: 5432
      REDIS_CONNECTION_HOST: "redis_hostname"
    volumes:
      - ./build/libs/user-login-0.0.1-SNAPSHOT.jar:/message-server-1.0.0.jar
    command: java -jar /message-server-1.0.0.jar
    depends_on:
      - db
      - redis
    networks:
      - app_network

  db:
    container_name: local_postgres
    hostname: postgres_hostname
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5433:5432'  # Map container port 5432 to host port 5433
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    container_name: local_redis
    hostname: redis_hostname
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    networks:
      - app_network

networks:
  app_network:

volumes:
  db:
  redis: